use dioxus::prelude::*;
use dioxus_free_icons::{Icon, icons::ld_icons::LdFileWarning};

use crate::components::{EmptyState, TopBar};

/// Generated by `scripts/third-party/generate.py`; compiled in so the list
/// always matches the build.
const NOTICES: &str = include_str!("../../../../../THIRD-PARTY-NOTICES.md");

/// One table row: a component or crate with its license.
#[derive(Debug, Clone, PartialEq)]
struct NoticeRow {
    name: String,
    version: String,
    license: String,
    copyright: String,
}

/// Full text of one license, titled with its SPDX id or component name.
#[derive(Debug, Clone, PartialEq)]
struct LicenseText {
    title: String,
    text: String,
}

#[derive(Debug, Clone, PartialEq, Default)]
struct Notices {
    components: Vec<NoticeRow>,
    crates: Vec<NoticeRow>,
    texts: Vec<LicenseText>,
}

/// Reads the parts of THIRD-PARTY-NOTICES.md the screen shows: the first
/// table (bundled components), the second (crates) and every `###`
/// section with a fenced license text. Headings and prose stay in the
/// file; the screen brings its own translated texts.
fn parse_notices(markdown: &str) -> Notices {
    let mut notices = Notices::default();
    let mut tables: Vec<Vec<NoticeRow>> = Vec::new();
    let mut in_table = false;
    let mut title = None::<String>;
    let mut fence = None::<String>;

    for line in markdown.lines() {
        if let Some(text) = fence.as_mut() {
            if line.trim_end() == "```" {
                notices.texts.push(LicenseText {
                    title: title.take().unwrap_or_default(),
                    text: std::mem::take(text).trim_end().to_string(),
                });
                fence = None;
            } else {
                text.push_str(line);
                text.push('\n');
            }
            continue;
        }
        if line.starts_with("```") {
            fence = Some(String::new());
        } else if let Some(heading) = line.strip_prefix("### ") {
            title = Some(heading.trim().to_string());
        } else if line.starts_with('|') {
            if !in_table {
                // The first row of a table is its header.
                tables.push(Vec::new());
                in_table = true;
                continue;
            }
            let cells = split_row(line);
            if cells.iter().all(|c| c.chars().all(|ch| ch == '-')) {
                continue;
            }
            if let [name, version, license, copyright] = cells.as_slice()
                && let Some(table) = tables.last_mut()
            {
                table.push(NoticeRow {
                    name: name.clone(),
                    version: version.clone(),
                    license: license.clone(),
                    copyright: copyright.clone(),
                });
            }
        } else {
            in_table = false;
        }
    }

    let mut tables = tables.into_iter();
    notices.components = tables.next().unwrap_or_default();
    notices.crates = tables.next().unwrap_or_default();
    notices
}

/// Cells of a `| a | b |` row; `\|` is a literal pipe inside a cell.
fn split_row(line: &str) -> Vec<String> {
    let inner = line.trim().trim_start_matches('|').trim_end_matches('|');
    let mut cells = vec![String::new()];
    let mut chars = inner.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            '\\' if chars.peek() == Some(&'|') => {
                chars.next();
                push_char(&mut cells, '|');
            }
            '|' => cells.push(String::new()),
            _ => push_char(&mut cells, ch),
        }
    }
    cells.into_iter().map(|c| c.trim().to_string()).collect()
}

fn push_char(cells: &mut [String], ch: char) {
    if let Some(cell) = cells.last_mut() {
        cell.push(ch);
    }
}

/// `/settings/licenses`: app version and the licenses of all third-party
/// software inside the app (SET-12).
#[component]
pub fn SettingsLicenses() -> Element {
    let notices = use_hook(|| parse_notices(NOTICES));

    rsx! {
        TopBar { title: t!("page.settings_licenses").to_string(), show_back: true }
        if notices.crates.is_empty() {
            EmptyState {
                title: t!("licenses.missing_title").to_string(),
                text: t!("licenses.missing_text").to_string(),
                Icon { icon: LdFileWarning, class: "h-8 w-8" }
            }
        } else {
            div { class: "mx-4 flex flex-col gap-6 pt-4 pb-4 safe-area-x",
                div { class: "flex flex-col gap-1 px-1",
                    p { class: "text-base font-semibold text-floral-white-50",
                        {t!("licenses.app_version", name = t!("app.name"), version = env!("CARGO_PKG_VERSION")).to_string()}
                    }
                    p { class: "text-sm text-floral-white-300", {t!("licenses.intro").to_string()} }
                }
                NoticeSection { title: t!("licenses.components").to_string(), rows: notices.components.clone() }
                NoticeSection {
                    title: t!("licenses.crates", count = notices.crates.len()).to_string(),
                    rows: notices.crates.clone(),
                }
                section { class: "flex flex-col gap-2",
                    SectionTitle { title: t!("licenses.texts").to_string() }
                    div { class: "flex flex-col overflow-hidden rounded-2xl border border-jet-black-800 bg-jet-black-900",
                        for license in notices.texts.iter() {
                            details {
                                key: "{license.title}",
                                class: "border-b border-jet-black-800 last:border-b-0",
                                summary { class: "flex min-h-12 cursor-pointer items-center px-4 py-2 text-base text-floral-white-50",
                                    "{license.title}"
                                }
                                pre { class: "whitespace-pre-wrap wrap-break-word px-4 pb-4 font-mono text-xs text-floral-white-300",
                                    "{license.text}"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

#[component]
fn SectionTitle(title: String) -> Element {
    rsx! {
        h2 { class: "px-1 text-xs font-semibold uppercase tracking-wide text-floral-white-400",
            "{title}"
        }
    }
}

/// Card listing components with version, license and copyright.
#[component]
fn NoticeSection(title: String, rows: Vec<NoticeRow>) -> Element {
    rsx! {
        section { class: "flex flex-col gap-2",
            SectionTitle { title }
            div { class: "flex flex-col overflow-hidden rounded-2xl border border-jet-black-800 bg-jet-black-900",
                for row in rows.iter() {
                    div {
                        key: "{row.name}@{row.version}",
                        class: "flex flex-col gap-0.5 border-b border-jet-black-800 px-4 py-2 last:border-b-0",
                        div { class: "flex items-baseline gap-2",
                            span { class: "min-w-0 flex-1 wrap-break-word text-base text-floral-white-50", "{row.name}" }
                            span { class: "shrink-0 text-sm tabular-nums text-floral-white-400", "{row.version}" }
                        }
                        span { class: "text-sm text-cerulean-300", "{row.license}" }
                        // "–" marks a missing notice in the file.
                        if row.copyright != "–" {
                            span { class: "wrap-break-word text-xs text-floral-white-400", "{row.copyright}" }
                        }
                    }
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_the_shipped_notices() {
        let notices = parse_notices(NOTICES);
        assert!(
            notices
                .components
                .iter()
                .any(|r| r.name.starts_with("SQLite"))
        );
        assert!(notices.crates.len() > 100);
        let ureq = notices.crates.iter().find(|r| r.name == "ureq").unwrap();
        assert_eq!(ureq.license, "MIT OR Apache-2.0");
        for title in ["MIT", "Apache-2.0", "ring", "Lucide Icons", "SQLite"] {
            assert!(
                notices
                    .texts
                    .iter()
                    .any(|t| t.title == title && !t.text.is_empty()),
                "{title} text missing"
            );
        }
    }

    #[test]
    fn parses_tables_and_fences() {
        let markdown = "# T\n\n| A | B | C | D |\n|---|---|---|---|\n| x | 1 | MIT | Copyright a \\| b |\n\n\
                        text\n\n| A | B | C | D |\n|---|---|---|---|\n| y | 2 | ISC | – |\n\n\
                        ### MIT\n\n```text\nline 1\n\nline 2\n```\n";
        let notices = parse_notices(markdown);
        assert_eq!(notices.components.len(), 1);
        assert_eq!(notices.components[0].copyright, "Copyright a | b");
        assert_eq!(notices.crates[0].name, "y");
        assert_eq!(
            notices.texts,
            vec![LicenseText {
                title: "MIT".into(),
                text: "line 1\n\nline 2".into()
            }]
        );
    }
}
