-- Initial schema: the data model of idee.md 4.1.
--
-- Conventions (idee.md 4, CORE-12):
-- * ids are UUIDv7 strings, generated by the app
-- * money = INTEGER amount in minor units + TEXT ISO 4217 code; never REAL
-- * decimals (rates, weights, percentages, quantities) are TEXT
-- * timestamps created_at/updated_at/deleted_at are INTEGER Unix milliseconds
-- * user-facing dates/times are TEXT ISO 8601 (occurred_at with UTC offset,
--   *_date as local YYYY-MM-DD)
-- * deletion is soft (deleted_at); sync columns origin_device_id,
--   created_by, updated_by are present on every synced table

CREATE TABLE settings (
    key        TEXT PRIMARY KEY NOT NULL,
    value      TEXT NOT NULL,
    updated_at INTEGER NOT NULL
);

CREATE TABLE person (
    id               TEXT PRIMARY KEY NOT NULL,
    name             TEXT NOT NULL,
    color            TEXT NOT NULL,
    avatar_path      TEXT,
    is_me            INTEGER NOT NULL DEFAULT 0 CHECK (is_me IN (0, 1)),
    note             TEXT,
    created_at       INTEGER NOT NULL,
    updated_at       INTEGER NOT NULL,
    deleted_at       INTEGER,
    origin_device_id TEXT NOT NULL,
    created_by       TEXT,
    updated_by       TEXT
);
CREATE UNIQUE INDEX person_single_me ON person (is_me) WHERE is_me = 1 AND deleted_at IS NULL;

CREATE TABLE category (
    id               TEXT PRIMARY KEY NOT NULL,
    name             TEXT NOT NULL,
    icon             TEXT NOT NULL,
    color            TEXT NOT NULL,
    is_default       INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
    sort_order       INTEGER NOT NULL DEFAULT 0,
    created_at       INTEGER NOT NULL,
    updated_at       INTEGER NOT NULL,
    deleted_at       INTEGER,
    origin_device_id TEXT NOT NULL,
    created_by       TEXT,
    updated_by       TEXT
);

-- "group" is an SQL keyword.
CREATE TABLE expense_group (
    id               TEXT PRIMARY KEY NOT NULL,
    name             TEXT NOT NULL,
    icon             TEXT NOT NULL,
    color            TEXT NOT NULL,
    description      TEXT,
    base_currency    TEXT NOT NULL,
    start_date       TEXT,
    end_date         TEXT,
    target_language  TEXT,
    archived         INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),
    created_at       INTEGER NOT NULL,
    updated_at       INTEGER NOT NULL,
    deleted_at       INTEGER,
    origin_device_id TEXT NOT NULL,
    created_by       TEXT,
    updated_by       TEXT
);

CREATE TABLE group_member (
    id               TEXT PRIMARY KEY NOT NULL,
    group_id         TEXT NOT NULL REFERENCES expense_group (id),
    person_id        TEXT NOT NULL REFERENCES person (id),
    default_weight   TEXT NOT NULL DEFAULT '1',
    joined_at        TEXT,
    left_at          TEXT,
    created_at       INTEGER NOT NULL,
    updated_at       INTEGER NOT NULL,
    deleted_at       INTEGER,
    origin_device_id TEXT NOT NULL,
    created_by       TEXT,
    updated_by       TEXT
);
CREATE UNIQUE INDEX group_member_unique ON group_member (group_id, person_id) WHERE deleted_at IS NULL;

CREATE TABLE payment_method (
    id                  TEXT PRIMARY KEY NOT NULL,
    name                TEXT NOT NULL,
    kind                TEXT NOT NULL,
    owner_person_id     TEXT REFERENCES person (id),
    last4               TEXT CHECK (last4 IS NULL OR (length(last4) = 4 AND last4 NOT GLOB '*[^0-9]*')),
    currency            TEXT,
    foreign_fee_percent TEXT,
    fixed_fee_minor     INTEGER,
    fixed_fee_currency  TEXT,
    color               TEXT NOT NULL,
    icon                TEXT NOT NULL,
    archived            INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),
    note                TEXT,
    created_at          INTEGER NOT NULL,
    updated_at          INTEGER NOT NULL,
    deleted_at          INTEGER,
    origin_device_id    TEXT NOT NULL,
    created_by          TEXT,
    updated_by          TEXT
);

CREATE TABLE exchange_rate (
    id               TEXT PRIMARY KEY NOT NULL,
    base             TEXT NOT NULL,
    quote            TEXT NOT NULL,
    rate             TEXT NOT NULL,
    rate_date        TEXT NOT NULL,
    fetched_at       INTEGER NOT NULL,
    source           TEXT NOT NULL,
    created_at       INTEGER NOT NULL,
    updated_at       INTEGER NOT NULL,
    deleted_at       INTEGER,
    origin_device_id TEXT NOT NULL,
    created_by       TEXT,
    updated_by       TEXT
);
CREATE INDEX exchange_rate_lookup ON exchange_rate (base, quote, rate_date);

CREATE TABLE receipt (
    id                   TEXT PRIMARY KEY NOT NULL,
    thumbnail_path       TEXT,
    ocr_raw_text         TEXT,
    ocr_engine           TEXT,
    ocr_confidence       REAL,
    detected_language    TEXT,
    detected_currency    TEXT,
    detected_total_minor INTEGER,
    detected_date        TEXT,
    detected_merchant    TEXT,
    parsed_at            INTEGER,
    status               TEXT NOT NULL DEFAULT 'new',
    created_at           INTEGER NOT NULL,
    updated_at           INTEGER NOT NULL,
    deleted_at           INTEGER,
    origin_device_id     TEXT NOT NULL,
    created_by           TEXT,
    updated_by           TEXT
);

CREATE TABLE receipt_image (
    id               TEXT PRIMARY KEY NOT NULL,
    receipt_id       TEXT NOT NULL REFERENCES receipt (id),
    position         INTEGER NOT NULL,
    path             TEXT NOT NULL,
    created_at       INTEGER NOT NULL,
    updated_at       INTEGER NOT NULL,
    deleted_at       INTEGER,
    origin_device_id TEXT NOT NULL,
    created_by       TEXT,
    updated_by       TEXT
);

CREATE TABLE expense (
    id                TEXT PRIMARY KEY NOT NULL,
    group_id          TEXT REFERENCES expense_group (id),
    title             TEXT NOT NULL,
    merchant          TEXT,
    category_id       TEXT REFERENCES category (id),
    occurred_at       TEXT NOT NULL,
    occurred_date     TEXT NOT NULL,
    total_minor       INTEGER NOT NULL,
    currency          TEXT NOT NULL,
    fx_rate_id        TEXT REFERENCES exchange_rate (id),
    total_base_minor  INTEGER NOT NULL,
    base_currency     TEXT NOT NULL,
    split_mode        TEXT NOT NULL,
    note              TEXT,
    location          TEXT,
    receipt_id        TEXT REFERENCES receipt (id),
    source            TEXT NOT NULL,
    reviewed          INTEGER NOT NULL DEFAULT 1 CHECK (reviewed IN (0, 1)),
    created_at        INTEGER NOT NULL,
    updated_at        INTEGER NOT NULL,
    deleted_at        INTEGER,
    origin_device_id  TEXT NOT NULL,
    created_by        TEXT,
    updated_by        TEXT
);
CREATE INDEX expense_by_group_time ON expense (group_id, occurred_at);

-- Amounts in the expense's currency.
CREATE TABLE expense_payment (
    id                TEXT PRIMARY KEY NOT NULL,
    expense_id        TEXT NOT NULL REFERENCES expense (id),
    person_id         TEXT NOT NULL REFERENCES person (id),
    payment_method_id TEXT REFERENCES payment_method (id),
    amount_minor      INTEGER NOT NULL,
    created_at        INTEGER NOT NULL,
    updated_at        INTEGER NOT NULL,
    deleted_at        INTEGER,
    origin_device_id  TEXT NOT NULL,
    created_by        TEXT,
    updated_by        TEXT
);
CREATE INDEX expense_payment_by_expense ON expense_payment (expense_id);

-- Input of the split mode; exactly one of weight/percent/amount_minor is set.
CREATE TABLE expense_share (
    id               TEXT PRIMARY KEY NOT NULL,
    expense_id       TEXT NOT NULL REFERENCES expense (id),
    person_id        TEXT NOT NULL REFERENCES person (id),
    weight           TEXT,
    percent          TEXT,
    amount_minor     INTEGER,
    created_at       INTEGER NOT NULL,
    updated_at       INTEGER NOT NULL,
    deleted_at       INTEGER,
    origin_device_id TEXT NOT NULL,
    created_by       TEXT,
    updated_by       TEXT
);
CREATE INDEX expense_share_by_expense ON expense_share (expense_id);

CREATE TABLE line_item (
    id                TEXT PRIMARY KEY NOT NULL,
    expense_id        TEXT NOT NULL REFERENCES expense (id),
    position          INTEGER NOT NULL,
    original_text     TEXT NOT NULL,
    translated_text   TEXT,
    user_text         TEXT,
    quantity          TEXT NOT NULL DEFAULT '1',
    unit_price_minor  INTEGER,
    total_price_minor INTEGER NOT NULL,
    kind              TEXT NOT NULL,
    ocr_confidence    REAL,
    edited_by_user    INTEGER NOT NULL DEFAULT 0 CHECK (edited_by_user IN (0, 1)),
    created_at        INTEGER NOT NULL,
    updated_at        INTEGER NOT NULL,
    deleted_at        INTEGER,
    origin_device_id  TEXT NOT NULL,
    created_by        TEXT,
    updated_by        TEXT
);
CREATE INDEX line_item_by_expense ON line_item (expense_id, position);

-- No rows for a line item = it belongs to everyone ("Allgemeinheit").
CREATE TABLE line_item_assignment (
    id               TEXT PRIMARY KEY NOT NULL,
    line_item_id     TEXT NOT NULL REFERENCES line_item (id),
    person_id        TEXT NOT NULL REFERENCES person (id),
    weight           TEXT NOT NULL DEFAULT '1',
    created_at       INTEGER NOT NULL,
    updated_at       INTEGER NOT NULL,
    deleted_at       INTEGER,
    origin_device_id TEXT NOT NULL,
    created_by       TEXT,
    updated_by       TEXT
);
CREATE INDEX line_item_assignment_by_item ON line_item_assignment (line_item_id);

CREATE TABLE cash_account (
    id               TEXT PRIMARY KEY NOT NULL,
    currency         TEXT NOT NULL,
    owner_person_id  TEXT NOT NULL REFERENCES person (id),
    group_id         TEXT REFERENCES expense_group (id),
    name             TEXT NOT NULL,
    created_at       INTEGER NOT NULL,
    updated_at       INTEGER NOT NULL,
    deleted_at       INTEGER,
    origin_device_id TEXT NOT NULL,
    created_by       TEXT,
    updated_by       TEXT
);

CREATE TABLE cash_movement (
    id               TEXT PRIMARY KEY NOT NULL,
    cash_account_id  TEXT NOT NULL REFERENCES cash_account (id),
    kind             TEXT NOT NULL,
    amount_minor     INTEGER NOT NULL,
    occurred_at      TEXT NOT NULL,
    expense_id       TEXT REFERENCES expense (id),
    fx_rate_id       TEXT REFERENCES exchange_rate (id),
    fee_minor        INTEGER,
    fee_currency     TEXT,
    note             TEXT,
    created_at       INTEGER NOT NULL,
    updated_at       INTEGER NOT NULL,
    deleted_at       INTEGER,
    origin_device_id TEXT NOT NULL,
    created_by       TEXT,
    updated_by       TEXT
);
CREATE INDEX cash_movement_by_account ON cash_movement (cash_account_id, occurred_at);

CREATE TABLE settlement (
    id                TEXT PRIMARY KEY NOT NULL,
    group_id          TEXT NOT NULL REFERENCES expense_group (id),
    from_person_id    TEXT NOT NULL REFERENCES person (id),
    to_person_id      TEXT NOT NULL REFERENCES person (id),
    amount_minor      INTEGER NOT NULL,
    currency          TEXT NOT NULL,
    payment_method_id TEXT REFERENCES payment_method (id),
    occurred_at       TEXT NOT NULL,
    note              TEXT,
    created_at        INTEGER NOT NULL,
    updated_at        INTEGER NOT NULL,
    deleted_at        INTEGER,
    origin_device_id  TEXT NOT NULL,
    created_by        TEXT,
    updated_by        TEXT
);
CREATE INDEX settlement_by_group ON settlement (group_id, occurred_at);

CREATE TABLE translation_cache (
    source_lang     TEXT NOT NULL,
    target_lang     TEXT NOT NULL,
    source_text     TEXT NOT NULL,
    translated_text TEXT NOT NULL,
    from_user       INTEGER NOT NULL DEFAULT 0 CHECK (from_user IN (0, 1)),
    updated_at      INTEGER NOT NULL,
    PRIMARY KEY (source_lang, target_lang, source_text)
);
