mod appearance;
mod categories;
mod data;
mod languages;
mod licenses;
mod payment_methods;
mod people;
mod person_detail;
mod profile;

pub use appearance::SettingsAppearance;
pub use categories::SettingsCategories;
pub use data::SettingsData;
pub use languages::SettingsLanguages;
pub use licenses::SettingsLicenses;
pub use payment_methods::SettingsPaymentMethods;
pub(crate) use people::PersonFormSheet;
pub use people::SettingsPeople;
pub use person_detail::PersonDetail;
pub use profile::Settings;
